### ISSUE TITLE
Mish Implementation

### ISSUE THREAD

**Issue by digantamisra98** [Tensor46/TensorMONK#52]
According to the code file, the implementation of Mish is as follows: 
```
def mish(tensor: torch.Tensor) -> torch.Tensor:
    return tensor * tensor.exp().add(1).log().tanh()
```
In my repository Mish implementation is like: 
```
def mish(tensor: torch.Tensor) -> torch.Tensor:
    return tensor * torch.tanh(F.softplus(tensor))
```

Is your implementation faster than mine??

Also, would appreciate if you included the paper link of Mish in the main Readme and in the activations readme, in the list of available activations, Mish is not present. 

The paper link is in my repository here - https://github.com/digantamisra98/Mish

**Comment by Tensor46** [comment]
Added the link in Readme. Not that it is fast but for clarity.
